version: '3.8'

services:
  spring-app:
    container_name: franchises-api-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USER_NAME=${DATABASE_USER_NAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
